spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 192.168.0.200:3306/gzxant_car_booking?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: gzxant
    password: gzxant1804