spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gzxant_portals?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: admin